# PyTorch Basics

** 
Installing and Importing torch Module
**

In [ ]:
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag

platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.0-{platform}-linux_x86_64.whl torchvision
    
import torch

** Constructing a matrix uninitialised **

In [2]:
x = torch.empty(5,3)
x

tensor(1.00000e-37 *
       [[ 1.1880,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [3]:
y = torch.zeros(2,3, dtype = torch.int64)
y

tensor([[ 0,  0,  0],
        [ 0,  0,  0]])

In [4]:
z = torch.rand(5,4)
z

tensor([[ 0.9274,  0.1235,  0.8077,  0.3810],
        [ 0.8291,  0.4798,  0.8357,  0.3483],
        [ 0.5771,  0.9746,  0.1086,  0.2710],
        [ 0.4449,  0.6819,  0.3522,  0.6951],
        [ 0.5630,  0.7553,  0.0698,  0.8245]])

** Constructing a Tensor directly from data**

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([ 5.5000,  3.0000])

** 
or create a tensor form another input tensor tensor. It take properties of that tensor unless they are mentioned explicitely
**

In [6]:
y = torch.randn_like(x)
z = torch.ones_like(x, dtype = torch.int32)
m = torch.ones_like(y, dtype = torch.double)
print(y)
print(z)
print(m)

tensor([-1.5921,  0.6024])
tensor([ 1,  1], dtype=torch.int32)
tensor([ 1.,  1.], dtype=torch.float64)


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [8]:
size = x.size()   # this is a tuple so supports all tuple operations
size

torch.Size([5, 3])

In [9]:
t1 = (1, 2, 3)
 
summ = size + t1
summ

torch.Size([5, 3, 1, 2, 3])

**
Doing Maths with Tensors
**

In [10]:
x = torch.rand(5,3)
x

tensor([[ 0.9601,  0.7718,  0.4931],
        [ 0.6171,  0.3201,  0.9414],
        [ 0.5830,  0.0858,  0.9556],
        [ 0.4622,  0.3555,  0.4825],
        [ 0.1041,  0.1525,  0.9043]])

In [11]:
y = torch.rand(5,3)
y

tensor([[ 0.5154,  0.1156,  0.9929],
        [ 0.3386,  0.6826,  0.3458],
        [ 0.6367,  0.7293,  0.3913],
        [ 0.4313,  0.4651,  0.7150],
        [ 0.3920,  0.7750,  0.8844]])

In [12]:
print(x + y)

tensor([[ 1.4755,  0.8874,  1.4859],
        [ 0.9556,  1.0027,  1.2872],
        [ 1.2198,  0.8151,  1.3469],
        [ 0.8935,  0.8206,  1.1974],
        [ 0.4960,  0.9275,  1.7887]])


In [13]:
addxy = torch.empty(5,3)
torch.add(x, y, out = addxy) # Assigns the output directly to tensor object 

tensor([[ 1.4755,  0.8874,  1.4859],
        [ 0.9556,  1.0027,  1.2872],
        [ 1.2198,  0.8151,  1.3469],
        [ 0.8935,  0.8206,  1.1974],
        [ 0.4960,  0.9275,  1.7887]])

In [14]:
addxy

tensor([[ 1.4755,  0.8874,  1.4859],
        [ 0.9556,  1.0027,  1.2872],
        [ 1.2198,  0.8151,  1.3469],
        [ 0.8935,  0.8206,  1.1974],
        [ 0.4960,  0.9275,  1.7887]])

**
Any operation that mutates a tensor in-place is post-fixed with an _ . For example: x.copy_(y), x.t_(), will change x.
**

In [15]:
#Any tensor to change in place the value postfix the method name with '_'

y.add_(x)

tensor([[ 1.4755,  0.8874,  1.4859],
        [ 0.9556,  1.0027,  1.2872],
        [ 1.2198,  0.8151,  1.3469],
        [ 0.8935,  0.8206,  1.1974],
        [ 0.4960,  0.9275,  1.7887]])

In [16]:
y

tensor([[ 1.4755,  0.8874,  1.4859],
        [ 0.9556,  1.0027,  1.2872],
        [ 1.2198,  0.8151,  1.3469],
        [ 0.8935,  0.8206,  1.1974],
        [ 0.4960,  0.9275,  1.7887]])

In [17]:
x = torch.randn(4,4)
x

tensor([[ 1.2260,  0.3180,  1.7270, -1.7345],
        [-0.1527, -0.2463, -1.3266,  0.2566],
        [ 0.0526,  0.3889, -0.4260,  0.4987],
        [-0.7883, -0.0256, -1.7268,  0.1150]])

**
Resizing: If you want to resize/reshape tensor, you can use torch.view:
**

In [18]:
y = x.view(16)
y

tensor([ 1.2260,  0.3180,  1.7270, -1.7345, -0.1527, -0.2463, -1.3266,
         0.2566,  0.0526,  0.3889, -0.4260,  0.4987, -0.7883, -0.0256,
        -1.7268,  0.1150])

In [19]:
z = x.view(-1, 8)
z

tensor([[ 1.2260,  0.3180,  1.7270, -1.7345, -0.1527, -0.2463, -1.3266,
          0.2566],
        [ 0.0526,  0.3889, -0.4260,  0.4987, -0.7883, -0.0256, -1.7268,
          0.1150]])

# NumPy Bridge
**
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.
**

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

In [20]:
a = torch.ones(5)
a

tensor([ 1.,  1.,  1.,  1.,  1.])

In [21]:
b = a.numpy()
print(b)
print(type(b))
b

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


array([1., 1., 1., 1., 1.], dtype=float32)

In [22]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


**Converting Numpy Array to Tensor Torch**

In [23]:
import numpy as np

a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [24]:
b = torch.from_numpy(a)
b

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

In [25]:
np.add(a, 3, out = a)
print(a)
print(b)

[4. 4. 4. 4. 4.]
tensor([ 4.,  4.,  4.,  4.,  4.], dtype=torch.float64)


# CUDA Tensors
**Tensors can be moved onto any device using the .to method.**

In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 2.2260,  1.3180,  2.7270, -0.7345],
        [ 0.8473,  0.7537, -0.3266,  1.2566],
        [ 1.0526,  1.3889,  0.5740,  1.4987],
        [ 0.2117,  0.9744, -0.7268,  1.1150]], device='cuda:0')
tensor([[ 2.2260,  1.3180,  2.7270, -0.7345],
        [ 0.8473,  0.7537, -0.3266,  1.2566],
        [ 1.0526,  1.3889,  0.5740,  1.4987],
        [ 0.2117,  0.9744, -0.7268,  1.1150]], dtype=torch.float64)
